# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: normalyser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'normalyser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10normalyser.proto\x12\nnormalyser\"@\n\x0bTransaction\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\"D\n\x13TransactionsRequest\x12-\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x17.normalyser.Transaction\"\x9a\x01\n\x12NormalisedMerchant\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0coriginalName\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x13\n\x0bsubCategory\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x16\n\x0eisSubscription\x18\x06 \x01(\x08\x12\r\n\x05\x66lags\x18\x07 \x03(\t\"Z\n\x1bNormalisedMerchantsResponse\x12;\n\x13normalisedMerchants\x18\x01 \x03(\x0b\x32\x1e.normalyser.NormalisedMerchant\"\x8f\x01\n\x11NormalisedPattern\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08merchant\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x11\n\tfrequency\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x14\n\x0cnextExpected\x18\x06 \x01(\t\x12\r\n\x05notes\x18\x07 \x01(\t\"W\n\x1aNormalisedPatternsResponse\x12\x39\n\x12normalisedPatterns\x18\x01 \x03(\x0b\x32\x1d.normalyser.NormalisedPattern2\xcf\x01\n\x11NormalyserService\x12]\n\x11normalizeMerchant\x12\x1f.normalyser.TransactionsRequest\x1a\'.normalyser.NormalisedMerchantsResponse\x12[\n\x10normalizePattern\x12\x1f.normalyser.TransactionsRequest\x1a&.normalyser.NormalisedPatternsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'normalyser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=32
  _globals['_TRANSACTION']._serialized_end=96
  _globals['_TRANSACTIONSREQUEST']._serialized_start=98
  _globals['_TRANSACTIONSREQUEST']._serialized_end=166
  _globals['_NORMALISEDMERCHANT']._serialized_start=169
  _globals['_NORMALISEDMERCHANT']._serialized_end=323
  _globals['_NORMALISEDMERCHANTSRESPONSE']._serialized_start=325
  _globals['_NORMALISEDMERCHANTSRESPONSE']._serialized_end=415
  _globals['_NORMALISEDPATTERN']._serialized_start=418
  _globals['_NORMALISEDPATTERN']._serialized_end=561
  _globals['_NORMALISEDPATTERNSRESPONSE']._serialized_start=563
  _globals['_NORMALISEDPATTERNSRESPONSE']._serialized_end=650
  _globals['_NORMALYSERSERVICE']._serialized_start=653
  _globals['_NORMALYSERSERVICE']._serialized_end=860
# @@protoc_insertion_point(module_scope)
