# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import normalyser_pb2 as normalyser__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in normalyser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NormalyserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.normalizeMerchant = channel.unary_unary(
                '/normalyser.NormalyserService/normalizeMerchant',
                request_serializer=normalyser__pb2.TransactionsRequest.SerializeToString,
                response_deserializer=normalyser__pb2.NormalisedMerchantsResponse.FromString,
                _registered_method=True)
        self.normalizePattern = channel.unary_unary(
                '/normalyser.NormalyserService/normalizePattern',
                request_serializer=normalyser__pb2.TransactionsRequest.SerializeToString,
                response_deserializer=normalyser__pb2.NormalisedPatternsResponse.FromString,
                _registered_method=True)


class NormalyserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def normalizeMerchant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def normalizePattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NormalyserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'normalizeMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.normalizeMerchant,
                    request_deserializer=normalyser__pb2.TransactionsRequest.FromString,
                    response_serializer=normalyser__pb2.NormalisedMerchantsResponse.SerializeToString,
            ),
            'normalizePattern': grpc.unary_unary_rpc_method_handler(
                    servicer.normalizePattern,
                    request_deserializer=normalyser__pb2.TransactionsRequest.FromString,
                    response_serializer=normalyser__pb2.NormalisedPatternsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'normalyser.NormalyserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('normalyser.NormalyserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NormalyserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def normalizeMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/normalyser.NormalyserService/normalizeMerchant',
            normalyser__pb2.TransactionsRequest.SerializeToString,
            normalyser__pb2.NormalisedMerchantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def normalizePattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/normalyser.NormalyserService/normalizePattern',
            normalyser__pb2.TransactionsRequest.SerializeToString,
            normalyser__pb2.NormalisedPatternsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
