name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: yarn install
        working-directory: analyser-api

      - name: Run unit tests
        run: yarn test
        working-directory: analyser-api

      - name: Check test results
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Tests failed. Blocking PR merge."
            exit 1
          fi
        working-directory: analyser-api
