name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./analyzer-api

      - name: Run unit tests
        run: pnpm test
        working-directory: ./analyzer-api

      - name: Check test results
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Tests failed. Blocking PR merge."
            exit 1
          fi
        working-directory: ./analyzer-api
